# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.2-node-browsers
      - image: circleci/mysql:5.7
      # - image: composer:latest

    #   working_directory: /work
    # steps:
    #   - run:
    #       name: Set timezone to Asia/Tokyo
    #       command: echo "date.timezone=Asia/Tokyo" > "$PHP_INI_DIR/conf.d/date_timezone.ini"
    #   - checkout
    #   - restore_cache:
    #       name: Restore composer cache
    #       keys:
    #         - composer-{{ .Environment.COMMON_CACHE_KEY }}-{{ checksum "composer.lock" }}
    #         - composer-{{ .Environment.COMMON_CACHE_KEY }}-
    #   - run:
    #       name: Setup requirements for continuous composer update
    #       command: composer global require enomotodev/circleci-composer-update-pr
    #   - deploy:
    #       name: Continuous composer update
    #       command: $COMPOSER_HOME/vendor/bin/circleci-composer-update-pr masanori0725 sanonokuma@gmail.com master

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout

      - run: sudo apt update # PHP CircleCI 2.0 Configuration File# PHP CircleCI 2.0 Configuration File sudo apt install zlib1g-dev libsqlite3-dev
      - run: sudo docker-php-ext-install zip

      # Install PHP Extension
      - run: sudo docker-php-ext-install pdo_mysql

      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "./books/composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          command: pwd
          command: ls
      - run:
          command: cd books && composer install -n --prefer-dist
      # - run: composer install -n --prefer-dist


      - save_cache:
          key: v1-dependencies-{{ checksum "./books/composer.json" }}
          paths:
            - ./vendor
      - restore_cache:
          keys:
            - node-v1-{{ checksum "./books/package.json" }}
            - node-v1-
      - run: yarn install
      - save_cache:
          key: node-v1-{{ checksum "./books/package.json" }}
          paths:
            - node_modules

      # prepare the database
          command: cd books && php artisan migrate --env=testing 

      # run tests with phpunit or codecept
      #- run: ./vendor/bin/phpunit
      # - run: ./books/vendor/bin/codecept build
      # - run: ./books/vendor/bin/codecept run
      # - run: php ./books/artisan --env=testing
      - run: php ./books/vendor/bin/phpunit --configuration=./books/phpunit.xml
